### ISSUE TITLE
[2.4] Autocopy really laggy

### ISSUE THREAD

**Issue by UltraBlackLinux** [TheCSMods/mc-chunk-copy#13] opened 2022-12-04 18:28 UTC
**Describe the bug**
Autocopy reduces my fps to 2

**To Reproduce**
Use autocopy

**Comment by TheCSDev** [comment] 2022-12-04 19:27
Hello and thank you for the report. Unfortunately I can not help you at the moment as that is nowhere near enough info for me to go off of. Upon further testing, it works perfectly fine for me, and it probably works fine for most other people as well. In other words, there are like a million factors (not literally) that play a role into whatvever could be causing the FPS drop for you. Like for example:
\- What OS do you have? (I don't think that one matters much tho)
\- What are your PC specs?
\- What mods do you have installed alongside this one?
\- Do any of the other mods conflict/break/mess with this mod's behavior in any way?
\- Have you tried running autocopy without the presence of any other mods?
\- Is the world around you being updated too frequently (such as block updates for example) or does it have a lot of complicated structures that overload this mod?
\- What is your render distance?
And I could keep going on and on, but those are just a few things worth mentioning. So unfortunately I'd need more info in order to help you diagnose your issue. The best advice I can think of right now is to recommend you a profiler mod such as [Spark](https://www.curseforge.com/minecraft/mc-mods/spark) that you could then use to run a profiler test and see what exactly is going on. Again, I am unable to reproduce this on my end, so I do not know what the issue is, so hopefully you can figure out what the issue is by trying out that profiler? Not sure. Also, sorry about the inconvenience, and have a great day.

**Comment by TheCSDev** [comment] 2022-12-05 19:22
Thank you for the info, I will look into it soon. In the meantime, regarding

> It seems like you are writing files every tick

The `ClientChunkManager` is a client-side game component that holds and manages chunk data locally on the client. Each time a chunk is "replaced" inside of the `ClientChunkMap` (a component that holds chunks), auto-copy copies the replaced chunk's data ([source](https://github.com/TheCSDev/mc-chunk-copy/blob/main/chunkcopy-fabric-1.19/src/main/java/thecsdev/chunkcopy/client/mixin/ClientChunkMapMixin.java)). It could be that something is replacing chunks frequently and triggering the copy each time? As far as I know, chunk replacement only takes place when loading/unloading a chunk. I will have look into it tho.

> I think you should buffer them and write them out every 5 seconds or so - This is unhealthy for drives)

I agree with that one. The reason I did not do that is because I only expected the auto-copy to be triggered by chunk loading and unloading only, which of course costs little to no performance. I guess I was wrong about assuming that? Regardless, definitely should limit the copying rate. Who knows, maybe Quilt or some other mod makes this behave differently?
Thanks again for the info. Will have a look into it.

**Comment by TheCSDev** [comment] 2022-12-05 19:51
Thank you so much for that Spark profiler log. I found the exact issue causing your FPS drop.

> It seems like you are writing files every tick

Turns out you were right about files being written every tick, except... it wasn't Chunk Copy that was causing it, it was another mod that constantly kept replacing chunks and their data every tick, thus triggering the auto copy each time that took place. And I just found out what mod is causing it (after making my PC suffer with 0 fps). I will share more info in a moment.

**Comment by TheCSDev** [comment] 2022-12-05 20:20
The cause was:

Index | Mod | ID | Version
-- | -- | -- | --
31 | Baritone | baritone-meteor | 1.19.2-SNAPSHOT

Why?
- The mod is doing something involving chunk data each time the Minecraft client ticks, causing `Chunk Copy` to trigger an `autoCopy` each time that takes place. In other words, this mod's `autoCopy` feature **conflicts with** `Baritone`.

Proof:
![Screenshot_1](https://user-images.githubusercontent.com/66475965/205734862-fbba2171-c605-423b-8fc1-0b618a10a82d.png)

**Comment by UltraBlackLinux** [comment] 2022-12-05 20:53
Oh interesting. Are you able to do anything on your side to prevent that from happening?

**Comment by TheCSDev** [comment] 2022-12-05 21:28
The best thing to do would be to just rewrite the mod and have it directly listen for chunk related packets from the server instead of listening for client-side changes to chunks. So alternative methods definitely are possible.

**Comment by TheCSDev** [comment] 2023-01-18 12:43
Forgot to close the issue then, so I will close it now. Resolving the issue would require rewriting the mod, so not much I can do here.

**Closed by TheCSDev** 2023-01-18 12:43 UTC
Labels: Bug
