### ISSUE TITLE
[2.4] Can't copy from server

### ISSUE THREAD

**Issue by LysiBee** [TheCSMods/mc-chunk-copy#14] opened 2023-01-18 12:24 UTC
**Describe the bug**
Can't paste chunks from my server to singleplayer world

**To Reproduce**
1. copy chunks from server
2. try to paste in SP world

**Comment by TheCSDev** [comment] 2023-01-18 12:39
Hello.
Thank you for the bug report, but there appears to be very little information to go off of here. This issue basically states that the one and only thing this mod is meant to do... doesn't do, and that's it, no further context. So how exactly am I meant to know what's wrong with such lack of information in this bug report?

**What I mean is:**
- Did you try following the instructions and going to the same coordinates in SP where you copied from in MP, **and then** executing the paste command?
- Were there any crashes or useful logs or crash reports?
- Did executing the `/chunkcopy paste ...` do nothing, even at the coordinates where you copied from?

Hopefully you just didn't try pasting at the same coordinates where you copied from, because I can't think of another reason as to why it doesn't work for you. If you did do everything as indended by the mod, then please go to the `.minecraft` directory or wherever else you have MC installed, and check the `mods > chunkcopy` directory to make sure chunks are actually getting copied. If chunks aren't actually getting copied, then your OS may be blocking the files from being created. I honestly don't know what else the issue could be.

Hopefully anything I mentioned above helps you resolve your issue. Have a good day!

**Comment by TheCSDev** [comment] 2023-01-19 11:20
Hello again.
Just wanted to let you know to feel free to let me know if the issue was resolved for you and if the above response helped resolve it. If the issue is still there despite the reply above, please do let me know and I'll try to look into what the issue is. Also apologies for the poor wording and if I didn't provide enough helpful information in my above response. If the issue is resolved by now, please also let me know so I can close this issue.

**Closed** 2023-01-20 13:33 UTC
Labels: Bug
